### ISSUE TITLE
Small RNA-seq

### ISSUE THREAD

**Issue by yfu** [yzheng74/permseq#2]
Dear Ye,

I read your impressive Perm-seq paper, which makes me wonder if this method is applicable to small RNA-seq read mapping. 

Small RNA-seq reads are very short (~18-35 nt long, single-end), and presumably, piRNAs (one kind of small RNAs) should have support from RNA-seq reads. Can this method use RNA-seq signals as the prior to determine mapping locations of multi-mapping small RNA reads? Can it handle split alignments of RNA-seq reads?

Thanks in advance!
Yu Fu

**Comment by yezhengSTAT** [comment]
Hi Yu,
Thanks for your interests in our work however I think the repetitive regions of RNA are due to splicing which is a different process from DNA repetitive regions. What you are looking for probably is RSEM created by Prof. Colin Dewey (http://deweylab.github.io/RSEM/). Hope it helps. ;)

**Comment by yfu** [comment]
Thanks anyway! It seems that RSEM is made to handle RNA-seq data, instead of using RNA-seq data to guide the mapping of small RNAs.

**Comment by yezhengSTAT** [comment]
@yfu I see your point. Permseq is basically a hierarchical Bayesian model. If you want to use RNA-seq signal as prior in assigning probability to the multi-mapping locations of one small RNA read which is aligned to repetitive regions of genome, mathematically, I think it will work. You may give it a try. However, I have very limited experience of dealing with RNA-seq, be careful with the difference between multi-mapping RNA-seq reads and multi-mapping ChIP-seq reads. 
Cheers,
Ye
