### ISSUE TITLE
Bowtie2

### ISSUE THREAD

**Issue by egenomics** [yzheng74/permseq#3]
Is there a way to use permseq with bowtie2 instead of bowtie1?

**Comment by yezhengSTAT** [comment]
Yes. You can do the alignment using bowtie2 outside permseq, then input the aligned sam file into permseq which will proceed from sam file. Be careful with the bowtie2 parameters. :)

**Comment by egenomics** [comment]
How do you input an aligned sam file with readAllocate? I can't find it in the manual.

What are the recommended parameters for bowtie2?
